name: Black Code Formatter Check

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter Check
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "--check src"
